# Form implementation generated from reading ui file 'ChatUI.ui'
#
# Created by: PyQt6 UI code generator 6.1.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


import PyQt6
from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(391, 411)
        sizePolicy = PyQt6.QtWidgets.QSizePolicy(PyQt6.QtWidgets.QSizePolicy.Policy.Fixed, PyQt6.QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(PyQt6.QtCore.QSize(391, 411))
        MainWindow.setMaximumSize(PyQt6.QtCore.QSize(391, 411))

        MainWindow.setWindowFlags(PyQt6.QtCore.Qt.WindowType.FramelessWindowHint)
        MainWindow.setAttribute(PyQt6.QtCore.Qt.WidgetAttribute.WA_TranslucentBackground)

        MainWindow.setAutoFillBackground(False)
        MainWindow.setStyleSheet("QMainWindow{\n"
"border-radius: 10px;\n"
"background-color: rgba(255, 255, 255, 255);\n"
"}")
        MainWindow.setDocumentMode(False)
        MainWindow.setTabShape(PyQt6.QtWidgets.QTabWidget.TabShape.Rounded)
        self.centralwidget = PyQt6.QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = PyQt6.QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(PyQt6.QtCore.QRect(0, 0, 391, 411))
        sizePolicy = PyQt6.QtWidgets.QSizePolicy(PyQt6.QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setMinimumSize(PyQt6.QtCore.QSize(391, 411))
        self.frame.setMaximumSize(PyQt6.QtCore.QSize(391, 411))
        self.frame.setStyleSheet("QFrame{\n"
"border-radius: 10px;\n"
"background-color: rgba(255, 255, 255, 255);\n"
"}")
        self.frame.setFrameShape(PyQt6.QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(PyQt6.QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.textBrowser = PyQt6.QtWidgets.QTextBrowser(self.frame)
        self.textBrowser.setEnabled(True)
        self.textBrowser.setGeometry(PyQt6.QtCore.QRect(10, 50, 371, 301))
        self.textBrowser.setStyleSheet("border: 1px solid rgba(70, 130, 180, 1);\n"
"border-radius: 3px;")
        self.textBrowser.setVerticalScrollBarPolicy(PyQt6.QtCore.Qt.ScrollBarPolicy.ScrollBarAsNeeded)
        self.textBrowser.setHorizontalScrollBarPolicy(PyQt6.QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.textBrowser.setObjectName("textBrowser")
        self.textEdit = PyQt6.QtWidgets.QTextEdit(self.frame)
        self.textEdit.setGeometry(PyQt6.QtCore.QRect(10, 360, 321, 37))
        self.textEdit.setStyleSheet("border: 1px solid rgba(70, 130, 180, 1);\n"
"border-radius: 3px;")
        self.textEdit.setObjectName("textEdit")
        self.pushButton = PyQt6.QtWidgets.QPushButton(self.frame)
        self.pushButton.setGeometry(PyQt6.QtCore.QRect(340, 360, 41, 37))
        font = PyQt6.QtGui.QFont()
        font.setFamily("Stencil")
        font.setPointSize(20)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("QPushButton{\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(32, 178, 170, 255), stop:0.55 rgba(0, 139, 139, 255), stop:0.98 rgba(0, 128, 129, 255), stop:1 rgba(70, 130, 180, 255));\n"
"border: 1px solid rgba(70, 130, 180, 1);\n"
"border-radius: 3px;\n"
"}\n"
"QPushButton:hover{\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(32, 178, 170, 200), stop:0.55 rgba(0, 139, 139, 200), stop:0.98 rgba(0, 128, 129, 200), stop:1 rgba(70, 130, 180, 200));\n"
"}\n"
"QPushButton:pressed{\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(32, 178, 170, 255), stop:0.55 rgba(0, 139, 139, 255), stop:0.98 rgba(0, 128, 129, 255), stop:1 rgba(70, 130, 180, 255));\n"
"}\n"
"")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = PyQt6.QtWidgets.QPushButton(self.frame)
        self.pushButton_2.setGeometry(PyQt6.QtCore.QRect(375, 0, 16, 16))
        self.pushButton_2.setStyleSheet("QPushButton{\n"
"background-color: rgba(255, 0, 0,255);\n"
"border: 1px solid rgb(193, 0, 0);\n"
"border-radius:3px;\n"
"border-top-right-radius: 5px;\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgba(255, 0, 0,200);\n"
"}\n"
"QPushButton:pressed{\n"
"background-color: rgba(255, 0, 0,255);\n"
"}\n"
"")
        self.pushButton_2.setObjectName("pushButton_2")
        self.label = PyQt6.QtWidgets.QLabel(self.frame)
        self.label.setGeometry(PyQt6.QtCore.QRect(20, 20, 131, 16))
        self.label.setStyleSheet("background-color: rgba(0, 0, 0, 0);\n"
"border-bottom:2px solid rgba(70, 130, 180, 1);\n"
"color: rgba(0,0,0,240);")
        self.label.setAlignment(PyQt6.QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        PyQt6.QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = PyQt6.QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", ">"))
        self.pushButton_2.setText(_translate("MainWindow", "X"))
        self.label.setText(_translate("MainWindow", "Имя собеседника"))
