# Form implementation generated from reading ui file 'RegistrationUI.ui'
#
# Created by: PyQt6 UI code generator 6.1.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


import PyQt6
from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(461, 520)
        MainWindow.setMinimumSize(PyQt6.QtCore.QSize(461, 500))
        MainWindow.setMaximumSize(PyQt6.QtCore.QSize(461, 520))

        MainWindow.setWindowFlags(PyQt6.QtCore.Qt.WindowType.FramelessWindowHint)
        MainWindow.setAttribute(PyQt6.QtCore.Qt.WidgetAttribute.WA_TranslucentBackground)

        self.centralwidget = PyQt6.QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = PyQt6.QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(PyQt6.QtCore.QRect(0, 0, 461, 561))
        sizePolicy = PyQt6.QtWidgets.QSizePolicy(PyQt6.QtWidgets.QSizePolicy.Policy.Expanding, PyQt6.QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setStyleSheet("background-color: rgba(255, 255, 255, 255);")
        self.frame.setFrameShape(PyQt6.QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(PyQt6.QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.label = PyQt6.QtWidgets.QLabel(self.frame)
        self.label.setGeometry(PyQt6.QtCore.QRect(140, 30, 181, 61))
        font = PyQt6.QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("")
        self.label.setObjectName("label")
        self.pushButton = PyQt6.QtWidgets.QPushButton(self.frame)
        self.pushButton.setGeometry(PyQt6.QtCore.QRect(105, 430, 251, 41))
        self.pushButton.setMinimumSize(PyQt6.QtCore.QSize(251, 41))
        self.pushButton.setMaximumSize(PyQt6.QtCore.QSize(251, 41))
        font = PyQt6.QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("QPushButton{\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(32, 178, 170, 255), stop:0.55 rgba(0, 139, 139, 255), stop:0.98 rgba(0, 128, 129, 255), stop:1 rgba(70, 130, 180, 255));\n"
"}\n"
"QPushButton:hover{\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(32, 178, 170, 200), stop:0.55 rgba(0, 139, 139, 200), stop:0.98 rgba(0, 128, 129, 200), stop:1 rgba(70, 130, 180, 200));\n"
"}\n"
"QPushButton:pressed{\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(32, 178, 170, 255), stop:0.55 rgba(0, 139, 139, 255), stop:0.98 rgba(0, 128, 129, 255), stop:1 rgba(70, 130, 180, 255));\n"
"}\n"
"")
        self.pushButton.setObjectName("pushButton")
        self.lineEdit = PyQt6.QtWidgets.QLineEdit(self.frame)
        self.lineEdit.setGeometry(PyQt6.QtCore.QRect(250, 130, 191, 31))
        font = PyQt6.QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit.setFont(font)
        self.lineEdit.setStyleSheet("\n"
"border: none;\n"
"border-bottom:2px solid rgba(70, 130, 180, 1);\n"
"color: rgba(0, 0, 0, 240);\n"
"padding-bottom: 7px;\n"
"\n"
"")
        self.lineEdit.setText("")
        self.lineEdit.setMaxLength(12)
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = PyQt6.QtWidgets.QLineEdit(self.frame)
        self.lineEdit_2.setGeometry(PyQt6.QtCore.QRect(20, 130, 191, 31))
        font = PyQt6.QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_2.setFont(font)
        self.lineEdit_2.setStyleSheet("background-color: rgba(0, 0, 0, 0);\n"
"border: none;\n"
"border-bottom:2px solid rgba(70, 130, 180, 1);\n"
"color: rgba(0, 0, 0, 240);\n"
"padding-bottom: 7px;\n"
"\n"
"")
        self.lineEdit_2.setInputMask("")
        self.lineEdit_2.setText("")
        self.lineEdit_2.setMaxLength(12)
        self.lineEdit_2.setFrame(True)
        self.lineEdit_2.setCursorPosition(0)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_3 = PyQt6.QtWidgets.QLineEdit(self.frame)
        self.lineEdit_3.setGeometry(PyQt6.QtCore.QRect(20, 240, 421, 31))
        font = PyQt6.QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_3.setFont(font)
        self.lineEdit_3.setStyleSheet("background-color: rgba(0, 0, 0, 0);\n"
"border: none;\n"
"border-bottom:2px solid rgba(70, 130, 180, 1);\n"
"color: rgba(0, 0, 0, 240);\n"
"padding-bottom: 7px;\n"
"\n"
"")
        self.lineEdit_3.setText("")
        self.lineEdit_3.setMaxLength(12)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.lineEdit_4 = PyQt6.QtWidgets.QLineEdit(self.frame)
        self.lineEdit_4.setGeometry(PyQt6.QtCore.QRect(20, 290, 421, 31))
        font = PyQt6.QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_4.setFont(font)
        self.lineEdit_4.setStyleSheet("background-color: rgba(0, 0, 0, 0);\n"
"border: none;\n"
"border-bottom:2px solid rgba(70, 130, 180, 1);\n"
"color: rgba(0, 0, 0, 240);\n"
"padding-bottom: 7px;\n"
"\n"
"")
        self.lineEdit_4.setText("")
        self.lineEdit_4.setMaxLength(12)
        self.lineEdit_4.setEchoMode(PyQt6.QtWidgets.QLineEdit.EchoMode.Password)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.lineEdit_5 = PyQt6.QtWidgets.QLineEdit(self.frame)
        self.lineEdit_5.setGeometry(PyQt6.QtCore.QRect(20, 180, 191, 31))
        font = PyQt6.QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_5.setFont(font)
        self.lineEdit_5.setStyleSheet("background-color: rgba(0, 0, 0, 0);\n"
"border: none;\n"
"border-bottom:2px solid rgba(70, 130, 180, 1);\n"
"color: rgba(0, 0, 0, 240);\n"
"padding-bottom: 7px;\n"
"\n"
"")
        self.lineEdit_5.setInputMask("")
        self.lineEdit_5.setText("")
        self.lineEdit_5.setMaxLength(15)
        self.lineEdit_5.setFrame(True)
        self.lineEdit_5.setCursorPosition(0)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.dateEdit = PyQt6.QtWidgets.QDateEdit(self.frame)
        self.dateEdit.setGeometry(PyQt6.QtCore.QRect(250, 180, 191, 31))
        font = PyQt6.QtGui.QFont()
        font.setPointSize(10)
        self.dateEdit.setFont(font)
        self.dateEdit.setMouseTracking(True)
        self.dateEdit.setContextMenuPolicy(PyQt6.QtCore.Qt.ContextMenuPolicy.DefaultContextMenu)
        self.dateEdit.setAutoFillBackground(False)
        self.dateEdit.setStyleSheet("border: none;\n"
"border-bottom:2px solid rgba(70, 130, 180, 1);\n"
"color: rgba(0, 0, 0, 240);\n"
"padding-bottom: 7px;\n"
"\n"
"\n"
"\n"
"")
        self.dateEdit.setFrame(True)
        self.dateEdit.setAlignment(PyQt6.QtCore.Qt.AlignmentFlag.AlignBottom|PyQt6.QtCore.Qt.AlignmentFlag.AlignLeading|PyQt6.QtCore.Qt.AlignmentFlag.AlignLeft)
        self.dateEdit.setButtonSymbols(PyQt6.QtWidgets.QAbstractSpinBox.ButtonSymbols.NoButtons)
        self.dateEdit.setMaximumDateTime(PyQt6.QtCore.QDateTime(PyQt6.QtCore.QDate(2021, 12, 31), PyQt6.QtCore.QTime(23, 59, 59)))
        self.dateEdit.setMinimumDateTime(PyQt6.QtCore.QDateTime(PyQt6.QtCore.QDate(1939, 9, 1), PyQt6.QtCore.QTime(0, 0, 0)))
        self.dateEdit.setCalendarPopup(False)
        self.dateEdit.setDate(PyQt6.QtCore.QDate(2001, 8, 9))
        self.dateEdit.setObjectName("dateEdit")
        self.lineEdit_6 = PyQt6.QtWidgets.QLineEdit(self.frame)
        self.lineEdit_6.setGeometry(PyQt6.QtCore.QRect(20, 340, 421, 31))
        font = PyQt6.QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_6.setFont(font)
        self.lineEdit_6.setStyleSheet("background-color: rgba(0, 0, 0, 0);\n"
"border: none;\n"
"border-bottom:2px solid rgba(70, 130, 180, 1);\n"
"color: rgba(0, 0, 0, 240);\n"
"padding-bottom: 7px;\n"
"\n"
"")
        self.lineEdit_6.setText("")
        self.lineEdit_6.setMaxLength(12)
        self.lineEdit_6.setEchoMode(PyQt6.QtWidgets.QLineEdit.EchoMode.Password)
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.pushButton_2 = PyQt6.QtWidgets.QPushButton(self.frame)
        self.pushButton_2.setGeometry(PyQt6.QtCore.QRect(445, 0, 16, 16))
        self.pushButton_2.setStyleSheet("QPushButton{\n"
"background-color: rgba(255, 0, 0,255);\n"
"border: 1px solid rgb(193, 0, 0);\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgba(255, 0, 0,200);\n"
"}\n"
"QPushButton:pressed{\n"
"background-color: rgba(255, 0, 0,255);\n"
"}\n"
"")
        self.pushButton_2.setObjectName("pushButton_2")
        self.label_2 = PyQt6.QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(PyQt6.QtCore.QRect(20, 379, 421, 31))
        self.label_2.setStyleSheet("color: rgb(255, 0, 0);")
        self.label_2.setText("")
        self.label_2.setAlignment(PyQt6.QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_2.setObjectName("label_2")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        PyQt6.QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = PyQt6.QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Sign up"))
        self.pushButton.setText(_translate("MainWindow", "Sign up"))
        self.lineEdit.setPlaceholderText(_translate("MainWindow", "Second name"))
        self.lineEdit_2.setPlaceholderText(_translate("MainWindow", "First name"))
        self.lineEdit_3.setPlaceholderText(_translate("MainWindow", "Username"))
        self.lineEdit_4.setPlaceholderText(_translate("MainWindow", "Password"))
        self.lineEdit_5.setPlaceholderText(_translate("MainWindow", "Country"))
        self.dateEdit.setSpecialValueText(_translate("MainWindow", "Date of Birth"))
        self.lineEdit_6.setPlaceholderText(_translate("MainWindow", "Password again"))
        self.pushButton_2.setText(_translate("MainWindow", "X"))
